default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: oauth-workshop_development

test:
  <<: *default
  database: oauth-workshop_test

production:
  <<: *default
  database: oauth-workshop_production